version: '3'

services:
    deluge:
      image: strm/deluge
      volumes:
        - "/data/torrent-files/:/dot-torrent"
        - "/data/torrent-input/:/autoadd"
        - "/data/torrent:/downloads"
        - "deluge-incomplete:/incomplete"
        - "deluge-config:/config"
      ports:
        - "8888:8112"
        - "58846:58846"

volumes:
  deluge-incomplete:
  deluge-config:
